taskwarrior: update to 2.30, fix compile
This is a cryptographically signed message in MIME format.

- fixes build errors (from buildbot logs):
build/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/liblua.so: undefined reference to `dlsym'
build/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/liblua.so: undefined reference to `dlerror'
build/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/liblua.so: undefined reference to `dlopen'
build/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib/liblua.so: undefined reference to `dlclose'
collect2: ld returned 1 exit status
- depends on liblua, libuuid
- use external libuuid instead of internal one
- update to taskwarrior 2.3.0

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>
[update from 2.20 to 2.30 and add libreadline dependency]
Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>