BB: lantiq:
MIPS: Fix rtlx build error.

      CC      arch/mips/kernel/rtlx.o
    /home/ralf/src/linux/upstream-sfr/arch/mips/kernel/rtlx.c: In function ‘file_write’:
    /home/ralf/src/linux/upstream-sfr/arch/mips/kernel/rtlx.c:439:23: error: unused variable ‘rt’ [-Werror=unused-variable]
    /home/ralf/src/linux/upstream-sfr/arch/mips/kernel/rtlx.c: In function ‘rtlx_module_init’:
    /home/ralf/src/linux/upstream-sfr/arch/mips/kernel/rtlx.c:523:3: error: implicit declaration of function ‘set_vi_handler’ [-Werror=implicit-function-declaration]
    cc1: all warnings being treated as errors

    Caused by 496ad9aa8ef448058e36ca7a787c61f2e63f0f54 [new helper:
    file_inode(file)].

    Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
Signed-off-by: Eddi De Pieri <eddi@depieri.net>